local Killsay = ui.add_checkbox("Become Annoying")
local Deathsay = ui.add_checkbox("Become Reverse Annoying")

function on_player_death(event)
    if not Killsay:get() then return end

    local phrases = {
        "killed by a hack with a lua ong",
        "killsay",
        "get got lol",
        "balls",
        "1", 
        "oh my god vot eto one tap! :P",
        "Loaded Onezor.lua[Free]",
        "Overwatch 2 Mod pack Rar file download :arrow_double_down: in desc free tool :fire: Downlooad For Free password 1234 Rar archive :white_check_mark:",
        "i'm am working on the cheat god hack over watch ~2~ mod pack for over watch ~2~ it will be excellent   . feature",
        "dont ping while i fap",
        "Do not.......................",
        "VAAAAAAAC !!!",
        "why would i kill myself when my thighs are so cute",
        "there is nothing wrong with wearing skirt, pantsu, thigh highs",
        "medusa wont wokr for me",
        "prediction.lua :(",
        "What the fuck is a Erp?",
        "Awwe, you're so cute when you're in pleasure~",
        "im sitting here thinking prims is that shit or i jus fell off lmfao my god",
        "im on prim... yea im dump",
        "get off ur colors[ImGuiCol_Button] ass hax!",
        "alt f4 rn",
        "wheres gs.dog users?",
        "killsay generated by ChatGPT",
        ":3 Industries",
        "!rs",
        "Can I have 100$ for my drug addiction please",
        "give me ur skin",
        "Extended backtracking should be useful for you",
        "yeah",
        "put a hex on a nigga n he wake up hella bruised",
        "me when the Scythnentic.lua says something when u die: :skull:",
        "This pandora lua ANNOYING AS FUCK!",
        "sleeping gato",
        "gimme pandora inv cracks ass",
        "gg",
        "I'm sure your bodypillow is very proud of you.",
        "LIFEEEEHAAAACK BITCH!!!",
        "its ok that u died give me a hug, all our cheats ass anywayz",
        "i'd love to cuddle you <3'",
        "You're such a pervert for filling me up with your baby batter Senpai~~",
        "Im on dat she/her pack",
        ":P",
        "Its just lua but c++",
        "Silly pandora, always needing luas to hit.. man! this cheat so good!!",
        "UwU u got uffed boy, me furry 1tap u masterrr OwO",
    }
    local userid = event:get_int("userid")
    local attacker = event:get_int("attacker")
    local local_player = engine.get_local_player()
    local attacker_entindex = engine.get_player_for_user_id(attacker)
    local victim_entindex = engine.get_player_for_user_id(userid)

    if attacker_entindex ~= local_player or victim_entindex == local_player then
        return
    end

    engine.execute_client_cmd("say " .. phrases[math.random(1, #phrases)])
end
callbacks.register("player_death", on_player_death)

function on_player_death(event)
    if not Deathsay:get() then return end

    local phrases2 = {
        "Im getting on vrchat fuuck thi is shit",
        "Dickrider >:(",
        "Deathsay",
        "Deathday AUUUUUUUUUGH",
        "FUUUUUUUUUUUUUCK",
        "You baimer me i fuck mom u die in hole and i cum in mom hole YEAH",
        "I didn't see you",
        "Man your mean",
        "My movement is shit",
        "EXTENDED BACKTRACKING IS FUCKING USELESS",
        "THI S CHEATA! HAAAACKRRRRRR",
        "!rs",
        "a bug flew on my keyboard sorry",
        "Ideal tickr bitch bitchfh BTICHER! i tick my hc 100 to hit u then i die! wtf!!!!!!!!!!!",
        "Voidhack sucks",
        "What just happrn bra",
        "They 1uff me auuuuuuuuuuuuuuuuuuuuuuh *moans*",
        "FAK U RAWETRIPORPERT RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "Omg pandora stoorppertt",
        "YOU ON NEVERLOSE PASTE U PASTER U PASSTE U SKID PASTE!! PAAAAAAAAAASTE",
        "Resonable gamesence user gg",
        "stoooooooooooooop not faaaaaaaaaair",
        "gg",
        "You on thats.gg you r just no",
        "Get off aimjunkies holy fart",
        "******!",
        "me rubbing my balls on the pavement",
        "Maybe U need my boot kit ? It’s not Malware just Importsnt for cheat.",
        "im a adopt me scammr",
        "idk im just doing random shit at this point",
        "wAAAAAAAAAAAAAAAAAAAAAAAAAAH!",
        "I love crocidiles to muchch",
        "ow",
        "i smoek backwards backwoods cigs",
        "The player that just now died is mad! - Scythnentic.Lua",
        "UwU OwO Me die master UwU",
    }
local userid = event:get_int("userid")
local attacker = event:get_int("attacker")
local local_player = engine.get_local_player()
local attacker_entindex = engine.get_player_for_user_id(attacker)
local victim_entindex = engine.get_player_for_user_id(userid)

if victim_entindex ~= local_player or attacker_entindex == local_player then
    return
end

engine.execute_client_cmd("say " .. phrases2[math.random(1, #phrases2)])
end
callbacks.register("player_death", on_player_death)
